### ISSUE TITLE
`PlayerData.instance.geo` => `PlayerData.instance.GetInt("geo")`

### ISSUE THREAD

**Issue by SFGrenade** [Korzer420/LoreMaster#1]
it is better for mod interoperability, if a mod ever changes the geo playerdata
https://github.com/Korzer420/LoreMaster/blob/dba9cb3da1c5fb8667fc2edd772fda5a7d451611/LoreMaster/CustomItem/TicketCost.cs#L13

**Comment by Korzer420** [comment]
There more occasions where I missed using the Get Methods. I'll get through each class again and correct it (if possible)
