### ISSUE TITLE
map issues

### ISSUE THREAD

**Issue by GaDemICE** [Korzer420/LoreMaster#14]
i don't know where else to contact about this so i guess i'll do it here.
because you cannot talk to npcs until you get enough lore buffs (which happens at around fungal wastes)  you cannot get maps from cornifer.  which i thought was "fine, i will get them later".
now i can talk to npcs, so i went and talked to all the tapes cornifer left behind in crossroads-greenpath-fungal wastes,  then i went back to iselda and not only does she not sell those maps she doesn't even sell a quill.  
is it intentional to play this mod without a proper map or do we get all of these later?

**Comment by Korzer420** [comment]
Hey, neither actually. You should be able to buy the maps as soon as you unlocked the listening ability. Are you sure Cornifer has left the map spots? Also, what does Iselda sell in your game?

**Comment by GaDemICE** [comment]
she only sold the compass and the map pins, for 0 geo. i cleared her and then she has the dialogue about me having bought everything she has. and this does not change even after i go talk to cornifer's tapes.

> Are you sure Cornifer has left the map spots?
as mentioned he has left his tapes in these 3 areas and i interacted with all 3 after i got the listening ability. i then met him in howling cliffs and got his map there so my only issue is the first 3 areas.

**Comment by Korzer420** [comment]
Oh sorry. Yeah I found the issue, I forgot to add the maps to the shop. Will add that with the new patch. Although expect this patch to release in the new year. Until then, you'd need to use the debug mod to obtain them, sorry.
