### ISSUE TITLE
laughable threat issues

### ISSUE THREAD

**Issue by GaDemICE** [Korzer420/LoreMaster#15]
laughable threat sometimes prevents opponents from appearing in "arena" rooms  (where the doors close and you have to kill a number of enemies to progress).  it happened in the queens gardens room with the flying ones and the platforms. they appeared at first but then i fell into the thorns.  when i respawned they had disappeared and didn't appear again.

it also makes rancid egg plants not able to be attacked if its active

and now lost kin doesn't appear in its dream arena, and i suspect its this lore skill  interfering again

i wish there was an option to toggle skills on/off like charms  when sitting on a bench for situations like these (update: just got the lore control so nvm this)
tried to remove them with a save file editor but it seems they are saved in another file
update: i was able to find and remove the zote skill inside the  user1.modded.json and now lost kin appeared. so its 100% an issue with this skill.

**Comment by Korzer420** [comment]
This is a known issue, but I'm currently don't have the time to work on this mod as a whole. Will fix that next year.

**Comment by GaDemICE** [comment]
yea no worries i beat the game now. it was pretty fun although some powers were interfering with gameplay so much i had to turn them off.  when next update happens i'll try on  a harder difficulty.  what are the differences between difficulties by the way?

**Comment by Korzer420** [comment]
Hardmode+ turns all abilities from the current zone which you didn't collect yet to twisted version of themselves. In heroic it is the same, although you can only remove the twisted abilities, but not actually gaining their normal effect.
