### ISSUE TITLE
Lore powers not appearing.

### ISSUE THREAD

**Issue by ShockDragonDelta** [Korzer420/LoreMaster#19]
Okay, so either I'm an idiot and not understanding how this mod works, or this mod is broken because I cannot get any lore powers to appear. I've tried many areas, but none grant me a power.

My current mod list:

Back Dash
Benchwarp
Bench Warp Fix
Charm Changer
Charm Crab
Charm Overhaul
Compass Always On
Debug Mod
Enemy HP Bar
Fake Peppino
Fyrenest
HKMirror
HKTool
HKTool Legacy
Infinite Notches
Item Changer
KorzUtils
Lore Master
LoreCore
Lost Artifacts
MagicUI
Mash Dash
Mash Slash
Menu Changer
Myla Flower
Nailmaster's Pride
Never Muffle
NIghtmare Spark
QoL
Quirrel Flower
Radiant Menu
Rainbow Eggs
Randomizer 4
RandomizerCore
Satchel
SFCore
Skill Upgrades
Soul Nail on Heavy Blow
The Glimmering Realm
Transcendence
Vasi

**Comment by Korzer420** [comment]
Try removing LoreCore. LoreCore and Lore Master both define the same locations, which is likely to cause issues.
